///arte_replace_by_id(arteId, playerId,name,gfx,userGfx, dmg,pow,waittime,cost, lvl,desc, ARTE_EFFECT_, TYPE_, duration);
i = argument0;
global.arte[i,ARTE_PLAYER] = argument1;
global.arte[i,ARTE_NAME] = argument2;
global.arte[i,ARTE_GFX] = argument3;
global.arte[i,ARTE_USER_GFX] = argument4;
global.arte[i,ARTE_DMG] = argument5;
global.arte[i,ARTE_POW] = argument6;
global.arte[i,ARTE_WAIT] = argument7;
global.arte[i,ARTE_COST] = argument8;
global.arte[i,ARTE_LVL] = argument9;
global.arte[i,ARTE_DESC] = argument10;
global.arte[i,ARTE_EFFECT] = argument11;
global.arte[i,ARTE_TYPE] = argument12;
global.arte[i,ARTE_DURATION] = argument13;
