///new_gfx(playerId, face, idle, run, defend, evade, hurt, down, cast, attack, attack up, attack side, attack down, attack air);
global.gfx[argument0, GFX_FACE] = argument1;
global.face[argument0] = argument1;
global.gfx[argument0, GFX_IDLE] = argument2;
global.gfx[argument0, GFX_RUN] = argument3;
global.gfx[argument0, GFX_DEF] = argument4;
global.gfx[argument0, GFX_EVADE] = argument5;
global.gfx[argument0, GFX_DMG] = argument6;
global.gfx[argument0, GFX_DEAD] = argument7;
global.gfx[argument0, GFX_CAST] = argument8;
global.gfx[argument0, GFX_ATTACK] = argument9;
global.gfx[argument0, GFX_ATTACK_UP] = argument10;
global.gfx[argument0, GFX_ATTACK_SIDE] = argument11;
global.gfx[argument0, GFX_ATTACK_DOWN] = argument12;
global.gfx[argument0, GFX_ATTACK_AIR] = argument13;
