///party_set(playerId, currentHp, arteName,arteName,arteName,arteName, arteName,arteName,arteName,arteName);
global.pty[argument0,PTY_HP] = argument1;
global.pty[argument0,PTY_A1_IDLE] = argument2;
global.pty[argument0,PTY_A1_UP] = argument3;
global.pty[argument0,PTY_A1_SIDE] = argument4;
global.pty[argument0,PTY_A1_DOWN] = argument5;
global.pty[argument0,PTY_A2_IDLE] = argument6;
global.pty[argument0,PTY_A2_UP] = argument7;
global.pty[argument0,PTY_A2_SIDE] = argument8;
global.pty[argument0,PTY_A2_DOWN] = argument9;
