//player_new(player, hp,sp, att, def,adef, spd, lvl,xp);
global.player[argument0,PLY_NAME] = argument1;
global.name[argument0] = argument1;
global.player[argument0,PLY_HP] = argument2;
global.player[argument0,PLY_SP] = argument3;
global.player[argument0,PLY_ATT] = argument4;
global.player[argument0,PLY_DEF] = argument5;
global.player[argument0,PLY_ADEF] = argument6;
global.player[argument0,PLY_SPD] = argument7;
global.player[argument0,PLY_LVL] = argument8;
global.player[argument0,PLY_XP] = argument9;
