///player_new(playerId, name, hp,sp, att,aatt,pow, def,adef, spd);
global.player[argument0,PLY_NAME] = argument1;
global.name[argument0] = argument1;
global.player[argument0,PLY_HP] = argument2;
global.player[argument0,PLY_SP] = argument3;
global.player[argument0,PLY_ATT] = argument4;
global.player[argument0,PLY_AATT] = argument5;
global.player[argument0,PLY_POW] = argument6;
global.player[argument0,PLY_DEF] = argument7;
global.player[argument0,PLY_ADEF] = argument8;
global.player[argument0,PLY_SPD] = argument9;
